name: huggingface          # Name of the conda environment
channels:
  - defaults          # Default channel for conda packages
dependencies:
  - python=3.11       # Specify the Python version
  - numpy             # Example of a conda package
  - pandas            # Another example of a conda package
  - transformers
  - datasets
  - ipykernel
  - pip:
    - torch 
    - torchvision 
    - torchaudio
    - protobuf