[project]
name = "huggingface"
version = "0.1.0"
description = "huggingface playground"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.8.1",
    "ipykernel>=6.29.5",
    "sentence-transformers>=5.0.0",
    "transformers>=4.53.2",
]
